openapi: 3.2.0
info:
  title: CoyoteGO Carrier - Offer APIs API
  description: '# Introduction


    Welcome to CoyoteGO''s API Documentation.'
  contact:
    name: API Management
    email: apimanagement@coyote.com
  version: v0.1.1.2549
  x-logo:
    url: https://coyote.com/wp-content/uploads/2020/02/APILogo-transparent.png
    altText: Coyote
servers:
- url: https://api.demo.coyote.com
  description: Demo
- url: https://api.coyote.com
  description: Production
- url: https://api-sandbox.coyote.com
  description: Sandbox
tags:
- name: Carrier - Offer APIs
paths:
  /api/v1/Offer/{id}:
    get:
      tags:
      - Carrier - Offer APIs
      summary: Get existing offer details
      description: Allows Coyote's Carrier to retrieve an existing offer details.
      parameters:
      - name: id
        in: path
        description: Offer id
        required: true
        schema:
          type: string
          description: Offer id
      responses:
        '200':
          description: Offer was found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferDetails'
              example:
                id: 602268460a1a33708429b165
                loadId: 28075798
                amount: 6000.0
                currency: PLN
                status: Accepted
            application/json:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferDetails'
              example:
                id: 602268460a1a33708429b165
                loadId: 28075798
                amount: 6000.0
                currency: PLN
                status: Accepted
            text/json:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferDetails'
              example:
                id: 602268460a1a33708429b165
                loadId: 28075798
                amount: 6000.0
                currency: PLN
                status: Accepted
            application/bson:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferDetails'
              example:
                id: 602268460a1a33708429b165
                loadId: 28075798
                amount: 6000.0
                currency: PLN
                status: Accepted
        '404':
          description: Offer not found
      operationId: getApiV1OfferById
      x-operation-id-source: derived
    delete:
      tags:
      - Carrier - Offer APIs
      summary: Remove offer
      description: Allows Coyote's Carrier to remove pending offer.
      parameters:
      - name: id
        in: path
        description: Offer id
        required: true
        schema:
          type: string
          description: Offer id
      responses:
        '200':
          description: Offer was successfully removed
        '400':
          description: Invalid request
        '404':
          description: Offer not found
      operationId: deleteApiV1OfferById
      x-operation-id-source: derived
  /api/v1/Offer/create:
    post:
      tags:
      - Carrier - Offer APIs
      summary: Create new offer
      description: Allows Coyote's Carrier to create new offer.
      requestBody:
        description: New offer request
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferRequest'
            example:
              loadId: 28070711
              amount: 5600.0
              currency: EUR
              webHookAddress: https://example.com/webhook
          application/json:
            schema:
              $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferRequest'
            example:
              loadId: 28070711
              amount: 5600.0
              currency: EUR
              webHookAddress: https://example.com/webhook
          text/json:
            schema:
              $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferRequest'
            example:
              loadId: 28070711
              amount: 5600.0
              currency: EUR
              webHookAddress: https://example.com/webhook
          application/*+json:
            schema:
              $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferRequest'
            example:
              loadId: 28070711
              amount: 5600.0
              currency: EUR
              webHookAddress: https://example.com/webhook
          application/bson:
            schema:
              $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferRequest'
            example:
              loadId: 28070711
              amount: 5600.0
              currency: EUR
              webHookAddress: https://example.com/webhook
      responses:
        '200':
          description: Offer was successfully created
          content:
            text/plain:
              schema:
                type: string
              example: 5f98845e46b1fb0a748827ee
            application/json:
              schema:
                type: string
              example: 5f98845e46b1fb0a748827ee
            text/json:
              schema:
                type: string
              example: 5f98845e46b1fb0a748827ee
            application/bson:
              schema:
                type: string
              example: 5f98845e46b1fb0a748827ee
        '400':
          description: Invalid request
        '409':
          description: Load is already inactive or booked
      operationId: postApiV1OfferCreate
      x-operation-id-source: derived
  /api/v1/Offer/{id}/book:
    post:
      tags:
      - Carrier - Offer APIs
      summary: Book an offer
      description: Allows Coyote's Carrier book an offer.
      parameters:
      - name: id
        in: path
        description: Offer id
        required: true
        schema:
          type: string
          description: Offer id
      responses:
        '200':
          description: Your Booking request was submitted. We will email a rate confirmation if your booking request is successful
        '400':
          description: Invalid request
        '404':
          description: Offer not found
      operationId: postApiV1OfferByIdBook
      x-operation-id-source: derived
  /api/v1/Offer/{id}/decline:
    post:
      tags:
      - Carrier - Offer APIs
      summary: Decline offer
      description: Allows Coyote's Carrier to decline countered offer.
      parameters:
      - name: id
        in: path
        description: Offer id
        required: true
        schema:
          type: string
          description: Offer id
      responses:
        '200':
          description: Offer was successfully declined
        '400':
          description: Invalid request
        '404':
          description: Offer not found
      operationId: postApiV1OfferByIdDecline
      x-operation-id-source: derived
components:
  schemas:
    Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferStatus:
      enum:
      - Unknown
      - Pending
      - Accepted
      - Countered
      - Confirmed
      - Canceled
      - Removed
      - Declined
      - Invalid
      type: string
      description: Offer status
    Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferDetails:
      required:
      - id
      type: object
      properties:
        id:
          type: string
          description: Offer id
        loadId:
          type: integer
          description: Available load Id
          format: int32
        amount:
          type: number
          description: Offer amount
          format: double
        currency:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.CurrencyType'
        status:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferStatus'
      additionalProperties: false
      description: Offer details
    Coyote.Systems.ExternalApi.Contracts.Models.Offer.CurrencyType:
      enum:
      - Undefined
      - USD
      - CAD
      - MXN
      - EUR
      - GBP
      - PLN
      type: string
      description: Currency Type
    Coyote.Systems.ExternalApi.Contracts.Models.Offer.OfferRequest:
      required:
      - amount
      - loadId
      type: object
      properties:
        loadId:
          type: integer
          description: Available load Id
          format: int32
        amount:
          type: number
          description: Offer amount
          format: double
        currency:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Offer.CurrencyType'
        webHookAddress:
          type:
          - string
          - 'null'
          description: Web hook url address
          format: uri
      additionalProperties: false
      description: Offer request
