openapi: 3.2.0
info:
  title: CoyoteGO Shipper - Tracking APIs API
  description: '# Introduction


    Welcome to CoyoteGO''s API Documentation.'
  contact:
    name: API Management
    email: apimanagement@coyote.com
  version: v0.1.1.2549
  x-logo:
    url: https://coyote.com/wp-content/uploads/2020/02/APILogo-transparent.png
    altText: Coyote
servers:
- url: https://api.demo.coyote.com
  description: Demo
- url: https://api.coyote.com
  description: Production
- url: https://api-sandbox.coyote.com
  description: Sandbox
tags:
- name: Shipper - Tracking APIs
paths:
  /api/v1/Trackings/{loadId}/stopdetails:
    get:
      tags:
      - Shipper - Tracking APIs
      summary: Gets all load stop details
      description: 'Allows Shippers to retrieve all load stop details for a given load, including facility information,

        as well as appointments, and tracking milestones.'
      parameters:
      - name: loadId
        in: path
        description: The requested load Id.
        required: true
        schema:
          type: integer
          description: The requested load Id.
          format: int32
      responses:
        '200':
          description: Successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.StopDetail'
              example:
                proNumber: PRONUMBER
                loadStops:
                - milestone:
                    driverArrivalDateTimeUtc: '2026-06-13T18:38:48.5416537Z'
                    trailerArriveDateTimeUtc: '2026-06-13T18:38:48.5416537Z'
                    trailerLoadedDateTimeUtc: '2026-06-13T18:38:48.5416538Z'
                    trailerEmptyDateTimeUtc: '2026-06-13T18:38:48.5416538Z'
                    driverDepartureDateTimeUtc: '2026-06-13T18:38:48.5416538Z'
                  sequence: 1
                  stopType: Pickup
                  facility:
                    name: Coyote Logistics
                    address:
                      line1: 2545 W Diversey Ave
                      line2: null
                      line3: null
                      postalCode: '60647'
                      cityName: Chicago
                      stateProvinceCode: IL
                      countryCode: USA
                    geoCoordinates:
                      latitude: 41.931674
                      longitude: -87.691939
                  appointment:
                    facilityOpenDateTimeUtc: '2026-06-14T18:33:48.5416535Z'
                    facilityCloseDateTimeUtc: '2026-06-14T18:33:48.5416534Z'
                    appointmentStartDateTimeUtc: '2026-06-13T18:38:48.5416528Z'
                    appointmentEndDateTimeUtc: '2026-06-13T19:13:48.5416534Z'
                - milestone:
                    driverArrivalDateTimeUtc: '2026-06-14T18:33:48.5416548Z'
                    trailerArriveDateTimeUtc: '2026-06-14T18:33:48.5416548Z'
                    trailerLoadedDateTimeUtc: '2026-06-14T18:33:48.5416549Z'
                    trailerEmptyDateTimeUtc: '2026-06-14T18:33:48.5416549Z'
                    driverDepartureDateTimeUtc: '2026-06-14T18:33:48.5416548Z'
                  sequence: 2
                  stopType: Delivery
                  facility:
                    name: Coyote Logistics
                    address:
                      line1: 1515 Wazee St
                      line2: null
                      line3: null
                      postalCode: '80202'
                      cityName: Denver
                      stateProvinceCode: CO
                      countryCode: USA
                    geoCoordinates:
                      latitude: 41.931674
                      longitude: -87.691939
                  appointment:
                    facilityOpenDateTimeUtc: '2026-06-14T18:33:48.5416545Z'
                    facilityCloseDateTimeUtc: '2026-06-14T18:33:48.5416545Z'
                    appointmentStartDateTimeUtc: '2026-06-14T18:33:48.5416544Z'
                    appointmentEndDateTimeUtc: '2026-06-14T18:33:48.5416544Z'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '503':
          description: Temporarily unavailable
      operationId: getApiV1TrackingsByLoadIdStopdetails
      x-operation-id-source: derived
  /api/v1/Trackings/{loadId}/summaries:
    get:
      tags:
      - Shipper - Tracking APIs
      summary: Gets load tracking summary
      description: 'Allows Shippers to retrieve a tracking summary view for a given load, including the latest location update,

        next stop details, and estimated arrival.'
      parameters:
      - name: loadId
        in: path
        description: The requested load Id.
        required: true
        schema:
          type: integer
          description: The requested load Id.
          format: int32
      responses:
        '200':
          description: Successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Summary'
              example:
                proNumber: PRONUMBER
                latestLocationStatus:
                  address:
                    line1: 2545 W Diversey Ave
                    line2: null
                    line3: null
                    postalCode: '60647'
                    cityName: Chicago
                    stateProvinceCode: IL
                    countryCode: USA
                  timestampUtc: '2026-06-13T18:33:48.5456031Z'
                  geoCoordinates:
                    latitude: 41.931674
                    longitude: -87.691939
                nextStop:
                  sequence: 2
                  stopType: Delivery
                  facility:
                    name: Coyote Logistics
                    address:
                      line1: 2545 W Diversey Ave
                      line2: null
                      line3: null
                      postalCode: '60647'
                      cityName: Chicago
                      stateProvinceCode: IL
                      countryCode: USA
                    geoCoordinates:
                      latitude: 41.931674
                      longitude: -87.691939
                  appointment:
                    facilityOpenDateTimeUtc: '2026-06-14T18:33:48.5456037Z'
                    facilityCloseDateTimeUtc: '2026-06-14T18:33:48.5456036Z'
                    appointmentStartDateTimeUtc: '2026-06-13T18:38:48.5456034Z'
                    appointmentEndDateTimeUtc: '2026-06-13T19:13:48.5456036Z'
                estimatedArrivalDateTimeUtc: '2026-06-13T18:43:48.5456018Z'
                nextStopDistance:
                  value: 10.0
                  unit: Miles
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '503':
          description: Temporarily unavailable
      operationId: getApiV1TrackingsByLoadIdSummaries
      x-operation-id-source: derived
  /api/v1/LocationStatuses/{loadId}:
    x-code-samples:
    - lang: Java
      source: 'HttpResponse response = Unirest.post("https://api-sandbox.coyote.com/api/v1/LocationStatuses/{loadId}")

        .header("content-type", "application/json")

        .header("Authorization", "Bearer TOKEN")

        .asString();'
    - lang: C#
      source: 'var client = new RestClient("https://api-sandbox.coyote.com/api/v1/LocationStatuses/{loadId}");

        var request = new RestRequest(Method.GET);

        request.AddHeader("Authorization", "Bearer TOKEN");

        request.AddHeader("content-type", "application/json");

        IRestResponse response = client.Execute(request);'
    - lang: curl
      source: "curl -X GET \\\nhttps://api-sandbox.coyote.com/api/v1/LocationStatuses/{loadId} \\\n-H 'Authorization: Bearer TOKEN' \\ \n-H 'Content-Type: application/json'"
    get:
      tags:
      - Shipper - Tracking APIs
      summary: Gets all tracking updates for a given load
      description: Allows Shippers to retrieve all location updates for a given load.
      parameters:
      - name: loadId
        in: path
        description: The requested load ID.
        required: true
        schema:
          type: integer
          description: The requested load ID.
          format: int32
      responses:
        '200':
          description: The tracking updates were successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.LocationStatus'
              example:
              - loadId: 12345
                address:
                  line1: 2545 W Diversey Ave
                  line2: null
                  city: Chicago
                  postalCode: '60647'
                  state: IL
                  countryCode: USA
                geoCoordinates:
                  latitude: 41.9316
                  longitude: -87.6921
                timestamp: '2026-06-13T18:33:48.487995Z'
              - loadId: 12345
                address:
                  line1: 1515 Wazee St
                  line2: null
                  city: Denver
                  postalCode: '80202'
                  state: CO
                  countryCode: USA
                geoCoordinates:
                  latitude: 39.734
                  longitude: -104.935
                timestamp: '2026-06-11T18:33:48.4879955Z'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: The tracking updates do not exist
      operationId: getApiV1LocationStatusesByLoadId
      x-operation-id-source: derived
  /api/v1/LocationStatuses/{loadId}/latest:
    x-code-samples:
    - lang: Java
      source: 'HttpResponse response = Unirest.post("https://api-sandbox.coyote.com/api/v1/LocationStatuses/{loadId}/latest")

        .header("content-type", "application/json")

        .header("Authorization", "Bearer TOKEN")

        .asString();'
    - lang: C#
      source: 'var client = new RestClient("https://api-sandbox.coyote.com/api/v1/LocationStatuses/{loadId}/latest");

        var request = new RestRequest(Method.GET);

        request.AddHeader("Authorization", "Bearer TOKEN");

        request.AddHeader("content-type", "application/json");

        IRestResponse response = client.Execute(request);'
    - lang: curl
      source: "curl -X GET \\\nhttps://api-sandbox.coyote.com/api/v1/LocationStatuses/{loadId}/latest \\\n-H 'Authorization: Bearer TOKEN' \\ \n-H 'Content-Type: application/json'"
    get:
      tags:
      - Shipper - Tracking APIs
      summary: Gets the latest tracking update for a given load
      description: Allows Shippers to retrieve the most recent location updates for a given load.
      parameters:
      - name: loadId
        in: path
        description: The requested load ID.
        required: true
        schema:
          type: integer
          description: The requested load ID.
          format: int32
      responses:
        '200':
          description: The tracking update was successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.LocationStatus'
              example:
                loadId: 12345
                address:
                  line1: 2545 W Diversey Ave
                  line2: null
                  city: Chicago
                  postalCode: '60647'
                  state: IL
                  countryCode: USA
                geoCoordinates:
                  latitude: 41.9316
                  longitude: -87.6921
                timestamp: '2026-06-13T18:33:48.4892069Z'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: The tracking update does not exist
      operationId: getApiV1LocationStatusesByLoadIdLatest
      x-operation-id-source: derived
components:
  schemas:
    Coyote.Systems.ExternalApi.Contracts.Models.StopType:
      enum:
      - None
      - Pickup
      - Delivery
      - ContainerDepotOrigin
      - ContainerDepotTermination
      - OriginRamp
      - DestinationRamp
      - OriginPort
      - DestinationPort
      - OriginAirport
      - DestinationAirport
      - CrossDock
      type: string
      description: Stop Types
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Unit:
      enum:
      - Miles
      - Kilometers
      type: string
      description: Distance Unit
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.StopDetail:
      type: object
      properties:
        proNumber:
          type:
          - string
          - 'null'
          description: ProNumber (LTL)
        loadStops:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.LoadStopProgress'
          description: Load Stops
      additionalProperties: false
      description: Stop Detail
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Facility:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: Name
        address:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.TrackingAddress'
        geoCoordinates:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.GeoCoordinates'
      additionalProperties: false
      description: Facility
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.LocationStatus:
      type: object
      properties:
        loadId:
          type: integer
          description: Load
          format: int32
        address:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Address'
        geoCoordinates:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.GeoCoordinates'
        timestamp:
          type: string
          description: Timestamp
          format: date-time
      additionalProperties: false
      description: Location Status
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Summary:
      type: object
      properties:
        proNumber:
          type:
          - string
          - 'null'
          description: ProNumber (LTL)
        latestLocationStatus:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Location'
        nextStop:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.LoadStop'
        estimatedArrivalDateTimeUtc:
          type:
          - string
          - 'null'
          description: ETA DateTime in Utc
          format: date-time
        nextStopDistance:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Distance'
      additionalProperties: false
      description: Summary
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.TrackingAddress:
      type: object
      properties:
        line1:
          type:
          - string
          - 'null'
          description: Line 1
        line2:
          type:
          - string
          - 'null'
          description: Line 2
        line3:
          type:
          - string
          - 'null'
          description: Line 3
        postalCode:
          type:
          - string
          - 'null'
          description: Postal Code
        cityName:
          type:
          - string
          - 'null'
          description: City Name
        stateProvinceCode:
          type:
          - string
          - 'null'
          description: State or Province Code
        countryCode:
          type:
          - string
          - 'null'
          description: Country Code
      additionalProperties: false
      description: Address
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.GeoCoordinates:
      type: object
      properties:
        latitude:
          type: number
          description: Latitude
          format: double
        longitude:
          type: number
          description: Longitude
          format: double
      additionalProperties: false
      description: GeoCoordinates
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Address:
      type: object
      properties:
        line1:
          type:
          - string
          - 'null'
          description: Line1
        line2:
          type:
          - string
          - 'null'
          description: Line2
        city:
          type:
          - string
          - 'null'
          description: City
        postalCode:
          type:
          - string
          - 'null'
          description: Postal Code
        state:
          type:
          - string
          - 'null'
          description: State
        countryCode:
          type:
          - string
          - 'null'
          description: Country Code
      additionalProperties: false
      description: Address
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.LoadStopProgress:
      type: object
      properties:
        milestone:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Milestone'
        sequence:
          type: integer
          description: Sequence
          format: int32
        stopType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.StopType'
        facility:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Facility'
        appointment:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Appointment'
      additionalProperties: false
      description: Load Stop
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Milestone:
      type: object
      properties:
        driverArrivalDateTimeUtc:
          type:
          - string
          - 'null'
          description: Driver Arrival DateTime in Utc
          format: date-time
        trailerArriveDateTimeUtc:
          type:
          - string
          - 'null'
          description: Trailer Arrive DateTime in Utc
          format: date-time
        trailerLoadedDateTimeUtc:
          type:
          - string
          - 'null'
          description: Trailer Loaded DateTime in Utc
          format: date-time
        trailerEmptyDateTimeUtc:
          type:
          - string
          - 'null'
          description: Trailer Empty DateTime in Utc
          format: date-time
        driverDepartureDateTimeUtc:
          type:
          - string
          - 'null'
          description: Driver Departure DateTime in Utc
          format: date-time
      additionalProperties: false
      description: Milestone
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Appointment:
      type: object
      properties:
        facilityOpenDateTimeUtc:
          type:
          - string
          - 'null'
          description: Facility Open DateTime in Utc
          format: date-time
        facilityCloseDateTimeUtc:
          type:
          - string
          - 'null'
          description: Facility Close DateTime in Utc
          format: date-time
        appointmentStartDateTimeUtc:
          type:
          - string
          - 'null'
          description: Appointment Start DateTime in Utc
          format: date-time
        appointmentEndDateTimeUtc:
          type:
          - string
          - 'null'
          description: Appointment End DateTime in Utc
          format: date-time
      additionalProperties: false
      description: Appointment
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Location:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.TrackingAddress'
        timestampUtc:
          type:
          - string
          - 'null'
          description: Timestamp in Utc
          format: date-time
        geoCoordinates:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.GeoCoordinates'
      additionalProperties: false
      description: Location
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Distance:
      type: object
      properties:
        value:
          type: number
          description: Value
          format: double
        unit:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Unit'
      additionalProperties: false
      description: Distance to Next Stop
    Coyote.Systems.ExternalApi.Contracts.Models.Tracking.LoadStop:
      type: object
      properties:
        sequence:
          type: integer
          description: Sequence
          format: int32
        stopType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.StopType'
        facility:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Facility'
        appointment:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Tracking.Appointment'
      additionalProperties: false
      description: Load Stop
