openapi: 3.2.0
info:
  title: CoyoteGO Shipper - Shipment APIs API
  description: '# Introduction


    Welcome to CoyoteGO''s API Documentation.'
  contact:
    name: API Management
    email: apimanagement@coyote.com
  version: v0.1.1.2549
  x-logo:
    url: https://coyote.com/wp-content/uploads/2020/02/APILogo-transparent.png
    altText: Coyote
servers:
- url: https://api.demo.coyote.com
  description: Demo
- url: https://api.coyote.com
  description: Production
- url: https://api-sandbox.coyote.com
  description: Sandbox
tags:
- name: Shipper - Shipment APIs
paths:
  /api/v1/Loads:
    post:
      tags:
      - Shipper - Shipment APIs
      summary: Submit a load request
      description: 'Allows Shippers to submit load build requests with relevant load information, including a Spot Quote ID. \

        *Note: Including a Spot Quote ID is currently unsupported in Europe.*'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Load'
            example:
              customer:
                referenceNumbers:
                - referenceNumberType: ShipmentNumber
                  referenceNumberValue: '123456'
                customerId: 0
              loadDetail:
                mode: TL
                equipmentType: V
                equipmentLength: 53
                requirements:
                - requirementType: Guaranteed
                  requirementValue: 'true'
                equipmentRequirements:
                - requirementType: LiftGate
                  requirementValue: 'true'
                - requirementType: XLoadBars
                  requirementValue: '6'
                stops:
                - sequence: 1
                  stopType: Pickup
                  facility:
                    name: Pick Up Facility
                    address:
                      line1: 123 Main St.
                      line2: null
                      line3: null
                      postalCode: '60647'
                      cityName: Chicago
                      stateProvinceCode: IL
                      countryCode: US
                    geoCoordinates: null
                    facilityContact:
                      name: PickUp Contact
                      phoneNumberCountryCode: null
                      phoneNumber: (123)456-7890
                      phoneNumberExtension: null
                      email: pickup.contact@email.com
                  stopRequirements:
                  - requirementType: DropTrailerAllowXHoursToUnload
                    requirementValue: '5'
                  - requirementType: Inside
                    requirementValue: 'true'
                  openDateTimeUtc: '2026-06-13T08:00:00Z'
                  closeDateTimeUtc: '2026-06-13T18:00:00Z'
                  appointmentStartDateTimeUtc: '2026-06-13T10:00:00Z'
                  appointmentEndDateTimeUtc: '2026-06-13T12:00:00Z'
                  referenceNumbers:
                  - ABC1234
                  - '123467'
                  - ABCXYZ
                  stopNotes: Sample instructions
                - sequence: 2
                  stopType: Delivery
                  facility:
                    name: Drop Off Facility
                    address:
                      line1: 123 Downers St.
                      line2: null
                      line3: null
                      postalCode: '50313'
                      cityName: Madison
                      stateProvinceCode: WI
                      countryCode: US
                    geoCoordinates: null
                    facilityContact:
                      name: Dropoff Contact
                      phoneNumberCountryCode: null
                      phoneNumber: (123)456-7890
                      phoneNumberExtension: null
                      email: dropoff.contact@email.com
                  stopRequirements:
                  - requirementType: DropTrailerAllowXHoursToUnload
                    requirementValue: '5'
                  - requirementType: Inside
                    requirementValue: 'true'
                  openDateTimeUtc: '2026-06-15T08:00:00Z'
                  closeDateTimeUtc: '2026-06-15T18:00:00Z'
                  appointmentStartDateTimeUtc: '2026-06-15T10:00:00Z'
                  appointmentEndDateTimeUtc: '2026-06-15T12:00:00Z'
                  referenceNumbers: null
                  stopNotes: null
                commodities:
                - description: Packages
                  poNumber: null
                  packagingType: Pallet
                  quantity: 100
                  palletCount: 5
                  weightUnit: Pounds
                  weight: 500.0
                  lengthUnit: Inches
                  length: 100.0
                  height: 50.0
                  width: 100.0
                  freightClass: null
                  nmfcNumber: null
                  nmfcSubNumber: null
                  cargoValue: 1000.0
                  stackable: false
                  temperatureUnit: null
                  temperatureSetting: null
                  preCoolTemperature: null
                  minimumTemperature: null
                  maximumTemperature: null
                  pickUpStopNumber: 1
                  deliveryStopNumber: 2
                  hazMatProperties:
                    hazMat: true
                    hazMatClass: 3
                    phoneNumber: (123)456-7890
                spotQuoteId: null
      responses:
        '200':
          description: Load request sent successfully
          content:
            text/plain:
              schema:
                type: string
              example: 5f98845e46b1fb0a748827ee
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: postApiV1Loads
      x-operation-id-source: derived
  /api/v1/Loads/{loadRequestId}/buildstatus:
    get:
      tags:
      - Shipper - Shipment APIs
      summary: Get load build status
      description: Allows Shippers to retrieve the current load build status for a previously submitted request.
      parameters:
      - name: loadRequestId
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
      responses:
        '200':
          description: The load build status was successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadRequestStatus'
              example:
                loadId: 123456
                status: Completed
                message: Load built successfully
                trackingUri: https://tracking.coyote.com?id=M6W8E9rVIDRZrGXTyObKpd3XHfMrfADfgH0OF3CXyhM%3D
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: getApiV1LoadsByLoadRequestIdBuildstatus
      x-operation-id-source: derived
  /api/v1/Loads/{loadId}:
    delete:
      tags:
      - Shipper - Shipment APIs
      summary: Cancel a load
      description: Allows Shippers to cancel a load that was previously submitted.
      parameters:
      - name: loadId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: The load was successfully cancelled
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: deleteApiV1LoadsByLoadId
      x-operation-id-source: derived
  /api/v1/Loads/search:
    get:
      tags:
      - Shipper - Shipment APIs
      summary: Search loads
      description: 'Based on a given search term, Coyote will return a list of all loads that match on any of the below reference number types associated to your loads.

        ```

        ReferenceNumberType:

        - "PRONumber"

        - "DeliveryNumber"

        - "AppointmentConfirmation"

        - "ProofOfDelivery"

        - "Reference"

        - "PoNumber"

        - "OrderNumber"

        - "CommercialInvoice"

        - "ShipmentNumber"

        - "MasterBillOfLading"

        - "BillOfLading"

        - "PickupNumber"

        ```'
      parameters:
      - name: searchTerm
        in: query
        description: Requested search term
        required: true
        schema:
          type: string
          description: Requested search term
      responses:
        '200':
          description: Loads successfully retrieved and returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.LoadSearchResult'
              example:
              - loadId: 19601171
                loadDate: '2026-06-13T13:33:48.4824219-05:00'
                loadStops:
                - sequence: 1
                  stopType: Pick Up
                  facility:
                    name: Printers Distributing Co., LLC
                    address:
                      line1: 270 Middle Road
                      line2: ''
                      line3: ''
                      cityName: Dallas
                      countryCode: USA
                      postalCode: '75221'
                      stateProvinceCode: TX
                    geoCoordinates:
                      latitude: 32.783
                      longitude: -96.8
                - sequence: 2
                  stopType: Delivery
                  facility:
                    name: Delivery Distributing Co., LLC
                    address:
                      line1: 3964 Shader Rd
                      line2: ''
                      line3: ''
                      cityName: Orlando
                      countryCode: USA
                      postalCode: '32808'
                      stateProvinceCode: FL
                    geoCoordinates:
                      latitude: 28.546
                      longitude: -81.378
                trackingUrl: null
        '204':
          description: Loads do not exist for given search term
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: getApiV1LoadsSearch
      x-operation-id-source: derived
components:
  schemas:
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.TrackingAddress:
      required:
      - cityName
      - countryCode
      - line1
      - postalCode
      - stateProvinceCode
      type: object
      properties:
        line1:
          type: string
          description: Line 1 (It must be 3-50 characters.)
        line2:
          type:
          - string
          - 'null'
          description: Line 2 (It must be 50 characters or less.)
        line3:
          type:
          - string
          - 'null'
          description: Line 3
        postalCode:
          type: string
          description: Postal Code
        cityName:
          type: string
          description: City Name
        stateProvinceCode:
          type: string
          description: State or Province Code
        countryCode:
          type: string
          description: Country Code
      additionalProperties: false
      description: Address
    Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.Facility:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: Name
        address:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.Address'
        geoCoordinates:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.GeoCoordinates'
      additionalProperties: false
      description: Load stop facility
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.HazMatProperties:
      type: object
      properties:
        hazMat:
          type: boolean
          description: HazMat
        hazMatClass:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.HazMatClass'
        phoneNumber:
          type:
          - string
          - 'null'
          description: PhoneNumber
      additionalProperties: false
      description: HazMat Properties
    Coyote.Systems.ExternalApi.Contracts.Models.LoadRequirementType:
      enum:
      - Guaranteed
      - Team
      - HazmatEndorsement
      - TankerEndorsement
      - Hvhr
      - HvhrPlus
      - ProtectFromFreeze
      - PartialLoad
      - DoubleBlind
      - DisasterRelief
      - TradeShow
      - TechTrackingRequired
      - Fast
      - PipOrPep
      - Neec
      - BondedCarrier
      - OverDimension
      - Ctpat
      - IntraMexico
      - CrossBorderMexico
      - BorderCrossingByCustomer
      - BorderCrossingByCoyote
      - FdaClearanceRequired
      - TransloadByCustomer
      - TransloadByCoyote
      - SecondaryBorderInspection
      - RepairReceiptRequiredForBreakdowns
      - Haccp
      - Seal
      - NoCameraPhonePhotosOfPaperwork
      - MustBeDedicatedTrailer
      - ThroughTrailerOnly
      - NoSubcontracting
      - NoTransitViaSwitzerland
      - SecureParkingInTransit
      - ThermographPrintout
      - TransitViaEurotunnel
      type: string
      description: Load requirement type
    Coyote.Systems.ExternalApi.Contracts.Models.Enums_FreightClass:
      enum:
      - Undefined
      - N50
      - N55
      - N60
      - N65
      - N70
      - N77PT5
      - N85
      - N92PT5
      - N100
      - N110
      - N125
      - N150
      - N175
      - N200
      - N250
      - N300
      - N400
      - N500
      type: string
      description: FreightClass
    Coyote.Systems.ExternalApi.Contracts.Models.HazMatClass:
      enum:
      - N3
      - N8
      - N9
      - NotApplicable
      - N2PT1
      - N2PT2
      - N4PT1
      - N4PT2
      - N5PT1
      - N6PT1P2
      - N6PT1P3
      - N1PT4
      - N1PT5
      - N1PT6
      type: string
      description: Hazmat class
    Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.GeoCoordinates:
      type: object
      properties:
        latitude:
          type:
          - number
          - 'null'
          description: Latitude
          format: double
        longitude:
          type:
          - number
          - 'null'
          description: Longitude
          format: double
      additionalProperties: false
      description: Geo coordinates
    Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.Address:
      type: object
      properties:
        line1:
          type:
          - string
          - 'null'
          description: Line 1
        line2:
          type:
          - string
          - 'null'
          description: Line 2
        line3:
          type:
          - string
          - 'null'
          description: Line 3
        cityName:
          type:
          - string
          - 'null'
          description: City name
        countryCode:
          type:
          - string
          - 'null'
          description: Country code
        postalCode:
          type:
          - string
          - 'null'
          description: Postal code
        stateProvinceCode:
          type:
          - string
          - 'null'
          description: State or province code
      additionalProperties: false
      description: Address
    Coyote.Systems.ExternalApi.Contracts.Models.Mode:
      enum:
      - TL
      - LTL
      - IMDL
      type: string
      description: Load Modes
    Coyote.Systems.ExternalApi.Contracts.Models.Enums_WeightUnitType:
      enum:
      - Pounds
      type: string
      description: Weight Units
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.StopType:
      enum:
      - Pickup
      - Delivery
      type: string
      description: Stop Types
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Load:
      required:
      - loadDetail
      type: object
      properties:
        customer:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Customer'
        loadDetail:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadDetail'
      additionalProperties: false
      description: Load information
    Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.LoadStop:
      type: object
      properties:
        sequence:
          type: integer
          description: Stop sequence
          format: int32
        stopType:
          type:
          - string
          - 'null'
          description: Stop type
        facility:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.Facility'
      additionalProperties: false
      description: Load stop
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadDetail:
      required:
      - commodities
      - equipmentLength
      - equipmentType
      - mode
      - stops
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Mode'
        equipmentType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Enums_EquipmentType'
        equipmentLength:
          type: integer
          description: Equipment length
          format: int32
        requirements:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadRequirement'
          description: Load requirements
        equipmentRequirements:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadEquipmentRequirement'
          description: Load equipment requirements
        stops:
          type: array
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadStop'
          description: List of load stops
        commodities:
          type: array
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadCommodity'
          description: List of commodities
        spotQuoteId:
          type:
          - string
          - 'null'
          description: "Spot Quote ID retrieved from Spot Quote requests API. For Truck Loads(TL) use the SpotQuoteId returned in TL Spot Quote request. For \nLess Than Truck Loads(LTL) use the CarrierQuoteId returned in LTL Spot Quote request."
      additionalProperties: false
      description: Load Details
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadEquipmentRequirement:
      type: object
      properties:
        requirementType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadEquipmentRequirementType'
        requirementValue:
          type:
          - string
          - 'null'
          description: Requirement value
      additionalProperties: false
      description: Load equipment requirement
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadStopRequirement:
      type: object
      properties:
        requirementType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadStopRequirementType'
        requirementValue:
          type:
          - string
          - 'null'
          description: Stop requirement value
      additionalProperties: false
      description: Load stop requirement
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadCommodity:
      required:
      - cargoValue
      - description
      - packagingType
      - quantity
      - weight
      type: object
      properties:
        description:
          type: string
          description: Item Description (Description must be 100 characters or less.)
        poNumber:
          type:
          - string
          - 'null'
          description: PO Number
        packagingType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.PackagingType'
        quantity:
          type: integer
          description: Number of units
          format: int32
        palletCount:
          type: integer
          description: 'Number of pallets relevant to commodity item


            **Required for LTL**'
          format: int32
        weightUnit:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Enums_WeightUnitType'
        weight:
          type: number
          description: 'Pallet weight in lbs(default) if not specified


            **Required for LTL**'
          format: double
        lengthUnit:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Enums_LengthUnitType'
        length:
          type: number
          description: 'Pallet length in inches


            **Required for LTL**'
          format: double
        height:
          type: number
          description: 'Pallet height in inches


            **Required for LTL**'
          format: double
        width:
          type: number
          description: 'Pallet width in inches


            **Required for LTL**'
          format: double
        freightClass:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Enums_FreightClass'
        nmfcNumber:
          type:
          - integer
          - 'null'
          description: NMFC Number
          format: int32
        nmfcSubNumber:
          type:
          - integer
          - 'null'
          description: NMFC Sub number
          format: int32
        cargoValue:
          type: number
          description: Cargo value
          format: double
        stackable:
          type: boolean
          description: Stackable
        temperatureUnit:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.TemperatureUnit'
        temperatureSetting:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.TemperatureSettingType'
        preCoolTemperature:
          type:
          - number
          - 'null'
          description: PreCool temperature if required
          format: double
        minimumTemperature:
          type:
          - number
          - 'null'
          description: Minimum temperature setting
          format: double
        maximumTemperature:
          type:
          - number
          - 'null'
          description: Maximum temperature setting
          format: double
        pickUpStopNumber:
          type: integer
          description: Pick up stop number for commodity
          format: int32
        deliveryStopNumber:
          type: integer
          description: Delivery stop number for commodity
          format: int32
        hazMatProperties:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.HazMatProperties'
      additionalProperties: false
      description: Commodity
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Customer:
      type: object
      properties:
        referenceNumbers:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.ReferenceNumber'
          description: List of reference numbers
        customerId:
          type: integer
          description: Customer Id
          format: int32
      additionalProperties: false
      description: Customer information
    Coyote.Systems.ExternalApi.Contracts.Models.PackagingType:
      enum:
      - NotApplicable
      - Case
      - Roll
      - Box
      - Sack
      - Bale
      - Carton
      - Coil
      - Drum
      - ToteBin
      - Bag
      - Bundle
      - Bulk
      - DryBulk
      - LiquidBulk
      - Barge
      - Barrel
      - BasketOrHamper
      - Beam
      - Bin
      - Bobbin
      - Bottle
      - BoxWithInnerContainer
      - Bucket
      - BulkBag
      - Cabinet
      - Cage
      - Can
      - CanCase
      - CarloadRail
      - Carboy
      - Cask
      - Chest
      - Container
      - ContainersOfBulkCargo
      - Core
      - Cradle
      - Crate
      - Cube
      - Cylinder
      - DoubleLengthRack
      - DoubleLengthSkid
      - DoubleLengthToteBin
      - DuffleBag
      - EngineContainer
      - Envelope
      - Firkin
      - Flask
      - FloBin
      - ForwardReel
      - Frame
      - GarmentsOnHangers
      - HalfStandardRack
      - HalfStandardToteBin
      - Hamper
      - Jar
      - Jug
      - Keg
      - Kit
      - KnockdownRack
      - KnockdownToteBin
      - Lifts
      - LinerBagDry
      - LinerBagLiquid
      - Loose
      - Lug
      - MilitaryVan
      - MixedTypePack
      - MultirollPack
      - MultiwallContainerSecuredToPallet
      - Noil
      - OnHangerOrRackInboxes
      - Overwrap
      - Package
      - Pail
      - Pallet
      - Pieces
      - Pims
      - PipeRack
      - Platform
      - PrivateVehicle
      - Rack
      - Reel
      - Skid
      - Sleeve
      - SlipSheet
      - Spool
      - Tank
      - ToteCan
      - Tray
      - TriwallBox
      - Truck
      - Tub
      - Tube
      - Unit
      - VanPack
      - IntermediateBulkContainers
      type: string
      description: Packaging types
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.ReferenceNumber:
      type: object
      properties:
        referenceNumberType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.Enums_MultipleNumberType'
        referenceNumberValue:
          type:
          - string
          - 'null'
          description: Reference number value. Can be alphanumeric (50 characters limit)
      additionalProperties: false
      description: Reference Numbers
    Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.LoadSearchResult:
      type: object
      properties:
        loadId:
          type: integer
          description: Coyote load Id
          format: int32
        loadDate:
          type: string
          description: Load date
          format: date-time
        loadStops:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadSearch.LoadStop'
          description: Load stops
        trackingUrl:
          type:
          - string
          - 'null'
          description: Tracking Url
          format: uri
      additionalProperties: false
      description: Load search response
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuildStatus:
      enum:
      - InProgress
      - Completed
      - Failed
      type: string
      description: Load build status
    Coyote.Systems.ExternalApi.Contracts.Models.Enums_EquipmentType:
      enum:
      - V
      - R
      type: string
      description: Equipment Type
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Contact:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
          description: Contact Name (It must be 50 characters or less.)
        phoneNumberCountryCode:
          type:
          - string
          - 'null'
          description: Phone number country code
        phoneNumber:
          type:
          - string
          - 'null'
          description: Phone number
        phoneNumberExtension:
          type:
          - string
          - 'null'
          description: Phone number extension
        email:
          type:
          - string
          - 'null'
          description: Contact email address
      additionalProperties: false
      description: Contact details
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Facility:
      required:
      - address
      - name
      type: object
      properties:
        name:
          type: string
          description: Name of the facility (It must be 50 characters or less.)
        address:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.TrackingAddress'
        geoCoordinates:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.GeoCoordinates'
        facilityContact:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Contact'
      additionalProperties: false
      description: Facility
    Coyote.Systems.ExternalApi.Contracts.Models.LoadEquipmentRequirementType:
      enum:
      - FoodGrade
      - PaperGrade
      - LiftGate
      - PalletJack
      - AirRide
      - TrailerXYearsOrNewer
      - XLoadLocks
      - XLoadBars
      - XLoadStraps
      - ETrack
      - Chains
      - NoRollDoor
      - NoReefer
      - NoLiftGate
      - DoubleTrailer
      - TripleTrailer
      - LoadOutTrailer
      - TowAway
      - LightweightEquipment
      - TandemSlide
      - DownloadableReefer
      - SpaceSaverReefer
      - TranslucentTop
      - Duraplate
      - VentedVan
      - FunctionalAirChute
      - RollDoorAllowed
      - XSideboards
      - ScaleUpToXPounds
      - ScaleUpToXKilograms
      - TrailerMustHaveAllWoodFloors
      - XlCode
      type: string
      description: Load Equipment requirement types
    Coyote.Systems.ExternalApi.Contracts.Models.LoadStopRequirementType:
      enum:
      - DropTrailerRequired
      - DropAndHook
      - DropTrailerAllowXHoursToUnload
      - PreloadDropTrailerXHoursInAdvance
      - Blind
      - Government
      - TWIC
      - EscortOrTWICRequired
      - UIIA
      - LiquorPermit
      - StrictAppt
      - NoWorkIns
      - NoEarlyDeliveries
      - NoSameDayReschedules
      - XRescheduleFee
      - XLateFee
      - ScaleEmpty
      - ScaleHeavy
      - XTankOfFuelAtShipper
      - LoadedToLegalWeight
      - NotAllowedOnDock
      - MustCheckinAsCoyote
      - NoLoadLocksOrStraps
      - MustSecureLoad
      - MustProvideAndApplySeal
      - ExitPass
      - EnglishSpeaking
      - SpanishSpeaking
      - USCitizen
      - ValidUSCommercialDriversLicenseHardcopy
      - OnsiteParkingAvailable
      - OvernightParkingAvailable
      - LegalScaleOnSite
      - SecureYard
      - HardHat
      - SafetyGlasses
      - EarPlugs
      - LongPants
      - LongSleeves
      - ClosedToeShoes
      - SteelToeShoes
      - SafetyVest
      - NoTankTops
      - NoAnimalsAllowed
      - PayLumperWCashTCheck
      - LumperReceiptRequired
      - NeedCoyoteApprovalToUseLumperService
      - PrepaidLumperService
      - LumperReceiptRequiredWithinXHours
      - TrailerDetentionAfterXDays
      - NoTrailerDetentionOrLayover
      - DetentionAuthFormRequired
      - TrailerInspectionFormRequired
      - Liftgate
      - Residential
      - LimitedAccess
      - SortAndSegregate
      - Inside
      - Tradeshow
      - UnpackDetrash
      - ScaleTicketMustBeSubmittedWithPaperwork
      - CarrierCannotContactFacility
      - WeightIsApproximate
      - PieceCountIsApproximate
      - DriverBlockAndBraceProduct
      - MustConfirmAllPosMatchRateCon
      - CleanCriminalRecordRequired
      - FacemaskRequired
      - NoOnsiteParking
      - NoOvernightParking
      - SafetyVideoRequired
      - WrittenSafetyTestRequired
      - PaperworkRequiredWithinXHours
      - CarrierNotifyBeforeArrival
      - AppointmentRequired
      - DoNotStack
      - PalletExchange
      - Fcfs
      type: string
      description: Load stop requirements
    Coyote.Systems.ExternalApi.Contracts.Models.Enums_LengthUnitType:
      enum:
      - Inches
      - Meters
      - Centimeters
      - Millimeters
      - Feet
      type: string
      description: Length Units
    Coyote.Systems.ExternalApi.Contracts.Models.Enums_MultipleNumberType:
      enum:
      - Reference
      - OrderNumber
      - BillOfLading
      - CommercialInvoice
      - MasterBOLNumber
      - PoNumber
      - ProNumber
      - ShipmentNumber
      type: string
      description: Multiple number types
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadRequestStatus:
      type: object
      properties:
        loadId:
          type: integer
          description: Coyote Load Id
          format: int32
        status:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuildStatus'
        message:
          type:
          - string
          - 'null'
          description: Success/Failure message
        trackingUri:
          type:
          - string
          - 'null'
          description: Tracking Uri
      additionalProperties: false
      description: Load status response
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadRequirement:
      type: object
      properties:
        requirementType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadRequirementType'
        requirementValue:
          type:
          - string
          - 'null'
          description: Requirement value
      additionalProperties: false
      description: ''
    Coyote.Systems.ExternalApi.Contracts.Models.TemperatureSettingType:
      enum:
      - Continuous
      - Cycle
      type: string
      description: Temperature settings
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadStop:
      required:
      - facility
      - sequence
      - stopType
      type: object
      properties:
        sequence:
          type: integer
          description: Stop sequence
          format: int32
        stopType:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.StopType'
        facility:
          $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.Facility'
        stopRequirements:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.LoadStopRequirement'
          description: Stop requirements
        openDateTimeUtc:
          type:
          - string
          - 'null'
          description: Facility open date/time in UTC
          format: date-time
        closeDateTimeUtc:
          type:
          - string
          - 'null'
          description: Facility close date/time in UTC
          format: date-time
        appointmentStartDateTimeUtc:
          type:
          - string
          - 'null'
          description: Appointment open date/time in UTC
          format: date-time
        appointmentEndDateTimeUtc:
          type:
          - string
          - 'null'
          description: Appointment close date/time in UTC
          format: date-time
        referenceNumbers:
          type:
          - array
          - 'null'
          items:
            type: string
          description: Reference numbers
        stopNotes:
          type:
          - string
          - 'null'
          description: Stop notes - special instructions relevant to stop (2500 characters limit)
      additionalProperties: false
      description: Load stop
    Coyote.Systems.ExternalApi.Contracts.Models.TemperatureUnit:
      enum:
      - Fahrenheit
      - Celsius
      type: string
      description: Temperature Units
    Coyote.Systems.ExternalApi.Contracts.Models.LoadBuilding.GeoCoordinates:
      required:
      - latitude
      - longitude
      type: object
      properties:
        latitude:
          type: number
          description: Latitude
          format: double
        longitude:
          type: number
          description: Longitude
          format: double
      additionalProperties: false
      description: GeoCoordinates
